#!/bin/bash

echo "🔧 Africa's Talking SMS Setup"
echo "================================"
echo ""
echo "📋 Steps to get your credentials:"
echo ""
echo "1. Go to: https://account.africastalking.com/apps/sandbox"
echo "2. Copy your USERNAME (usually 'sandbox')"
echo "3. Copy your API KEY (click 'Generate' if needed)"
echo ""
echo "4. Then run:"
echo "   nano backend/.env"
echo ""
echo "5. Update these lines:"
echo "   AFRICASTALKING_USERNAME=sandbox"
echo "   AFRICASTALKING_API_KEY=paste_your_key_here"
echo ""
echo "6. Save and restart backend:"
echo "   cd backend && node src/index.js"
echo ""
echo "✅ SMS will then send to real phones!"
